// Generated Feb 24, 2019 12:02:22 AM by Hibernate Tools 5.3.6.Final

package net.nunolages.philosophytrends.domain;

/**
 * DtwStatistics generated by hbm2java
 */
public class DtwStatistics implements java.io.Serializable {

	private DtwStatisticsId id;
	private TbwPhilosopher tbwPhilosophers;

	public DtwStatistics() {
	}

	public DtwStatistics(DtwStatisticsId id, TbwPhilosopher tbwPhilosophers) {
		this.id = id;
		this.tbwPhilosophers = tbwPhilosophers;
	}

	public DtwStatisticsId getId() {
		return this.id;
	}

	public void setId(DtwStatisticsId id) {
		this.id = id;
	}

	public TbwPhilosopher getTbwPhilosophers() {
		return this.tbwPhilosophers;
	}

	public void setTbwPhilosophers(TbwPhilosopher tbwPhilosophers) {
		this.tbwPhilosophers = tbwPhilosophers;
	}

}
