// Generated Feb 24, 2019 12:02:22 AM by Hibernate Tools 5.3.6.Final

package net.nunolages.philosophytrends.domain;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TbwPhilosophers generated by hbm2java
 */
@Entity
@Table(name = "tbw_philosopher")
public class TbwPhilosopher implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue
    @Column(name = "id")
	private int id;
	
	@Column(name = "name")
	private String name;

	public TbwPhilosopher() {
	}

	public TbwPhilosopher(int id, String name) {
		this.id = id;
		this.name = name;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}
}
