// Generated Feb 24, 2019 12:02:22 AM by Hibernate Tools 5.3.6.Final

package net.nunolages.philosophytrends.domain;

import java.util.HashSet;
import java.util.Set;

/**
 * TbwPhilosophers generated by hbm2java
 */
public class TbwPhilosophers implements java.io.Serializable {

	private int id;
	private String name;
	private Set dtwStatisticses = new HashSet(0);

	public TbwPhilosophers() {
	}

	public TbwPhilosophers(int id, String name) {
		this.id = id;
		this.name = name;
	}

	public TbwPhilosophers(int id, String name, Set dtwStatisticses) {
		this.id = id;
		this.name = name;
		this.dtwStatisticses = dtwStatisticses;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set getDtwStatisticses() {
		return this.dtwStatisticses;
	}

	public void setDtwStatisticses(Set dtwStatisticses) {
		this.dtwStatisticses = dtwStatisticses;
	}

}
